name: BeMatch

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - App/BeMatch/**/*
      - Packages/BeMatch/**/*
      - Packages/SDK/**/*
      - .github/workflows/bematch.yml
      - Makefile
  pull_request:
    paths:
      - App/BeMatch/**/*
      - Packages/BeMatch/**/*
      - Packages/SDK/**/*
      - .github/workflows/bematch.yml
      - Makefile

env:
  PLATFORM_IOS: iOS Simulator,name=iPhone 15 Pro,OS=17.0.1
  BEMATCH_FILE_FIREBASE_STAGING: ${{ secrets.BEMATCH_FILE_FIREBASE_STAGING }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: ls /Applications
      - run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - uses: irgaly/xcode-cache@v1
        with:
          key: bematch-xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: bematch-xcode-cache-deriveddata-${{ github.workflow }}-
      - run: make bootstrap
      - run: xcodebuild build -workspace BeMatch.xcworkspace -scheme "App (Staging project)" -skipMacroValidation -destination platform="${{ env.PLATFORM_IOS }}" | xcpretty
